spring.application.name=hospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=Aayush@123


server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto= create

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql


#Security config

#spring.security.user.name=Aayush
#spring.security.user.password=Pass


jwt.secretKey = ajfhbaksd10924801asofh4o91sifnc3948nad2u34901fhoad12394dfj038dhocha